name = "Edge"
license = "MIT"
licenselink = "https://github.com/mpaluchowski/hugo-edge/blob/master/LICENSE.md"
description = "Theme for my personal cycling-themed blog."
homepage = "https://cycling.paluchowski.com/"
tags = ["blog", "responsive"]
features = []
min_version = "0.43"

[author]
    name = "Michał Paluchowski"
    homepage = "https://cycling.paluchowski.com/"
